POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "matheus",
    "email": "matheus@email.com",
    "password": "102030a"
}

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email": "matheus@email.com",
    "password": "102030a"
}

### 

GET http://localhost:3333/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYWVhMWM5My1mMTcyLTQ4YmMtYjE4My05Mzc5ZGFlYjg4NjYiLCJpYXQiOjE3NTk3ODg0Njh9.ChrzjCweBD_f5kD5tRQC223vhYsDxFh5k0OoFOija80

###

POST http://localhost:3000/gyms
Content-Type: application/json

{
    "title": "Academia Central",
    "description": "Academia completa com musculação e crossfit",
    "phone": "123456789",
    "latitude": -10.912345,
    "longitude": -37.070123
}

### Buscar academias próximas
POST http://localhost:3000/gyms/nearby
Content-Type: application/json

{
    "latitude": -10.912345,
    "longitude": -37.070123
}

### Buscar academias pelo nome/termo (página 1)
GET http://localhost:3000/gyms/nearby?latitude=-10.912345&longitude=-37.070123
Content-Type: application/json

### Buscar academias por termo (página 1)
GET http://localhost:3000/gyms/search?q=Central&page=1
Content-Type: application/json

### Criar um check-in
POST http://localhost:3000/check-ins/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json
Authorization: Bearer <SEU_TOKEN>

{
    "latitude": -10.912345,
    "longitude": -37.070123
}

### Histórico de check-ins do usuário (página 1)
GET http://localhost:3000/check-ins/history?page=1
Content-Type: application/json
Authorization: Bearer <SEU_TOKEN>

### Métricas do usuário (quantidade de check-ins)
GET http://localhost:3000/check-ins/metrics
Content-Type: application/json
Authorization: Bearer <SEU_TOKEN>

### Validar um check-in
PATCH http://localhost:3000/check-ins/validate/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json
Authorization: Bearer <SEU_TOKEN>